FROM williamyeh/scala:latest 
MAINTAINER elongeau

# installation de paquet Debian
RUN apt-get update && \
        apt-get install -y --force-yes \
	vim \
	curl \
	cmake \
	zsh \
	git \
	xclip \
	desktop-file-utils \
	expect \
	luajit \
	lua-bitop \
	lua-lpeg \
	tmux \
	libswt-gtk-3-java-gcj \
	xvfb \
	bzr \
  sudo \
  vim-nox \
  vim-gtk \
  vim-gnome \
  vim-athena 
